export enum UserAction {
    SET_USER_TOKEN = 'SET_USER_TOKEN',
    SET_USER_NAME = 'SET_USER_NAME',
    SET_USER_ID = 'SET_USER_ID',
    SET_IS_LOGGED = 'SET_IS_LOGGED',
    SET_ERROR_MSG = 'SET_ERROR_MSG',
    SET_REGISTER_ERROR = 'SET_REGISTER_ERROR',
}